### ISSUE TITLE
BUL = BGR

### ISSUE THREAD

**Issue by nilsnolde** [alephdata/languagecodes#4]
In the `ISO2_MAP`, Bulgaria is listed as `bul`, but according to https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3, the right alpha-3 code would be `bgr`.

**Comment by nilsnolde** [comment]
Huh.. I'm just realizing I've been assuming this is for ISO 3166-1 codes, but it's not, it's for ISO 639-1 codes.. should've read a bit more carefully..

**Comment by pudo** [comment]
@nilsnolde check out https://github.com/alephdata/countrynames next door :)
